### ISSUE TITLE
💡 [FILTER REQUEST] - matomo

### ISSUE THREAD

**Issue by spirillen** [LanikSJ/webannoyances#11]
### Description

Have found a new matomo scripts https://github.com/mypdns/adblocker-rules/commit/f7fb9b26d5639eca8f23b06e409d167536851734 I recommend you to add to your filters

### Ad Blocker Name

uBlock Origin

### Browser Name

Mozilla Firefox

### Site URL

```bash
bibliotek.dk
```

### Screenshots

```bash
not needed
```

### OS

Linux

**Comment by LanikSJ** [comment]
I'm going to try and get that in by end of the week.
