### ISSUE TITLE
README

### ISSUE THREAD

**Issue by spirillen** [LanikSJ/webannoyances#2]
### Describe the issue

tl;dr 

Have you updated the `README.md` for links to external sources you might not have access to? IE in the bottom?

Also a general "Other issues" template should maybe be different from a template for submitting rules.

thanks for the update in https://github.com/yourduskquibbles/webannoyances/issues/516 and welcome to the club of #blacklist maintainers, now you know what to spend every seconds of your live not at work :smiling_face_with_tear:

**Comment by LanikSJ** [comment]
Fixed in #2 I think.
