### ISSUE TITLE
dressinsparkles.com

### ISSUE THREAD

**Issue by Sonic5435325** [LanikSJ/webannoyances#29]
### Description

sticky top

### Ad Blocker Name

uBlock Origin

### Browser Name

Mozilla Firefox

### Site URL

```bash
http://www.dressinsparkles.com/2014/11/
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Linux

**Comment by LanikSJ** [comment]
```dressinsparkles.com##.PageList```
That took care of it for me, it's more of an annoyance if you ask me.

**Comment by Sonic5435325** [comment]
> `dressinsparkles.com##.PageList` That took care of it for me, it's more of an annoyance if you ask me.
> 
> I'm also see lots of 503 errors for iFrames I'm assuming are blocked. If you want to get rid of those `dressinsparkles.com##[src*="shopsensewidget.shopstyle.com"]`

`##.PageList` is pretty much a navigator to the site, I wouldn't hide the entire element.

**Comment by Sonic5435325** [comment]
Alright I took a closer look at it and these filters work almost perfectly:
`dressinsparkles.com##.navbar` (Just serves as a gap at the top of the page)
`dressinsparkles.com##.tabs-outer:style(position: absolute !important;)`

**Comment by Sonic5435325** [comment]
Getting back to this: When the header element gets unstickified, the background of it will shrink and it'll go a bit downwards. This can be fixed by applying `top: -30px` to it, but I don't know about the background issue.
